# Generated by Django 3.1.7 on 2021-02-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
